# Generated by Django 5.2 on 2025-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment140Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.IntegerField()),
                ('text', models.TextField()),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('retweet_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('hashtags', models.JSONField(blank=True, null=True)),
                ('mentions', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
