# Generated by Django 5.2 on 2025-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('author_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('retweet_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('quote_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('tweet_count', models.IntegerField(default=0)),
                ('listed_count', models.IntegerField(default=0)),
                ('hashtags', models.TextField(blank=True)),
                ('mentions', models.TextField(blank=True)),
                ('geo_location', models.CharField(blank=True, default='', max_length=255)),
                ('cleaned_text', models.TextField(blank=True)),
                ('sentiment_score', models.IntegerField(default=2)),
            ],
        ),
    ]
