# Generated by Django 5.2 on 2025-04-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
