# Generated by Django 5.2 on 2025-04-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tweet_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
