# Generated by Django 5.2 on 2025-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tweet_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
