# Generated by Django 5.2 on 2025-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tweet_follower_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='follower_count',
        ),
        migrations.AddField(
            model_name='tweet',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
