# Generated by Django 5.2 on 2025-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tweet_follower_count_tweet_followers_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentiment140Tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_bot',
            field=models.BooleanField(null=True),
        ),
    ]
